### ISSUE TITLE
Documentation Link in README.md Redirects to Repository Home Instead of Documentation Page

### ISSUE THREAD

**Issue by moutasemalakkad** [landing-ai/vision-agent#125]
**Issue:**
The link to the Vision Agent Library Docs in the README.md file redirects to the top of the repository instead of opening the documentation.

**Steps to Reproduce:**
1. Navigate to the Vision Agent GitHub repository.
2. Click on the "Vision Agent Library Docs" link under the Documentation section.

**Expected Result:**

The link should direct to the documentation page.

**Actual Result:**
The link redirects to the top of the repository.

**Environment:**
Browser: Chrome
Operating System: Mac 

Please update the link to point to the correct documentation page.
<img width="1680" alt="Screenshot 2024-06-10 at 12 37 34 PM" src="https://github.com/landing-ai/vision-agent/assets/39648266/4a08b91f-a56f-44ed-8197-a4da8fb140bf">

**Comment by dillonalaird** [comment]
Strange, I am not able to reproduce it on my end. Can you try accessing this link? https://landing-ai.github.io/vision-agent/ that is the link in the README.md file

**Comment by moutasemalakkad** [comment]
Working now. Seems like it was a caching issue on my end. Thanks!
