### ISSUE TITLE
grounding_dino tool

### ISSUE THREAD

**Issue by monjha** [landing-ai/vision-agent#175]
Hi,
is this a typo? https://github.com/landing-ai/vision-agent/blob/f2705a909370b7aa2775b38c8274f9fdf2efeb01/vision_agent/tools/tools.py#L1268 You don't have gdino in tool list. I wasn't able to call it ever.

**Comment by dillonalaird** [comment]
No that's not a typo. We found OWLv2 and Florence2 generally work better than grounding DINO so we removed it from the tool list. That list is just want VisionAgent sees when it's trying to figure out which tools to use. Grounding DINO is still in the tools.py file though so you can call it manually if you want:

```python
import vision_agent.tools as T

image = T.load_image("image.png")
T.grounding_dino("person", image)
```
