### ISSUE TITLE
Error with the example/custom_tools/run_custom_tool.py

### ISSUE THREAD

**Issue by yungyuantseng** [landing-ai/vision-agent#196]
Hi, I'm trying on your interesting project, but I've meet some problems.
I found that VisionAgent has no attribute 'chat_with_work_flow' in the `example/custom_tools/run_custom_tool.py`
but there is a chat_with_work_flow in VisionAgentCoder.
Can you help me check this kind of issue?
Very appreciate that!
The version of the VisionAgent is  0.2.101
![image](https://github.com/user-attachments/assets/7ca468cd-208c-4f8c-a2f0-3a3db77d08dd)

**Comment by dillonalaird** [comment]
Let me update that example, sorry we have changed the old `VisionAgent` to `VisionAgentCoder`. `VisionAgentCoder` will generate the python code you want with `chat_with_workflow` while `VisionAgent` exposes `chat_with_code` and allows you to have conversations.
